# Generated by Django 3.2.2 on 2023-12-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DealerShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('name', models.CharField(max_length=70)),
                ('year', models.PositiveIntegerField()),
                ('price', models.FloatField(default=0.0, max_length=11)),
                ('img', models.URLField()),
                ('colors', models.JSONField()),
                ('version', models.JSONField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('delaerships', models.ManyToManyField(to='vehicles.DealerShip')),
            ],
        ),
    ]
