# Generated by Django 3.2.2 on 2023-12-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_auto_20231216_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='delaerships',
            new_name='dealerships',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='dealerships',
            field=models.ManyToManyField(to='vehicles.Dealership'),
        ),
    ]
