# Generated by Django 3.2.2 on 2023-12-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20231217_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='dealerships',
            field=models.ManyToManyField(to='vehicles.Dealership'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.FloatField(default=0.0, max_length=11)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=80)),
                ('for_clients', models.BooleanField(default=True)),
                ('dealerships', models.ManyToManyField(to='vehicles.Dealership')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.FloatField(default=0.0, max_length=11)),
                ('description', models.TextField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('dealerships', models.ManyToManyField(to='vehicles.Dealership')),
            ],
        ),
    ]
